config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/users/sign_in')
  devise_for :users
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  resources :home, :dashboard
  resources :organizations do 
    resource :users
    resources :projects, only: [:index]
  end
  resources :projects do
   resources :project_activities
  end
  resources :project_activities, as: "assigned_projects", assigned: true
  resources :users do
    resources :projects
    get :autocomplete_user_email, :on => :collection
  end
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
    @organizations = current_user.organizations
  end
  
  def new
    hash =  eval(params[:params_attr]) rescue {}
    project_id = params[:project_id].join(',') if params[:project_id].class == Array
    project_id = params[:project_id] if project_id.nil?
    path =  hash["project_id"] = project_id if hash["controller"] == "project_activities" and hash["project_id"].present? and hash["project_id"].present? and not params[:set_org].present?
    path = hash["id"] = current_organization.id if hash["controller"] == "organizations" and hash["id"].present? and params[:set_org].present?
       
    redirect_to hash.present? ? hash : dashboard_index_path
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
-# = link_to "create Org", new_organization_path
-# = link_to "Organization List", organizations_path
-# = link_to "assigned project",  user_projects_path(user_id: current_user.id)
%h1 
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{colspan: "3"} Link
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.name, organization #data: {params: {organization_id: organization.id}.to_param}
        %td= organization.description
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Projects', organization_projects_path(organization)
        - # %td= link_to 'Edit', edit_organization_path(organization)
        - # %td= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= text_field_tag "text", '', class: "textarea"
%script#dropboxjs{"data-app-key" => "tdmsa1byd6usjf9", :src => "https://www.dropbox.com/static/api/2/dropins.js", :type => "text/javascript"}

.subNavCnt
  %h1
    Upload dropbox images
  .moreLinks
    
  .clear

.sectionCnt
  
  .formLayout
    .row
      #dropbox
      .clear

:javascript
  $(document).ready(function(){
    $("#uploadText").hide()
  });
  options_list = {
    success: function(files) {
       
      var name = new Array();

      for (i = 0; i < files.length; i++) {
       name[i] = files[i].link
      }
      $("#uploadText").show();
      $.ajax({
          url: "/products/update_dropbox_bulk_image_upload.js?data="+name,
          type: "GET",

      }).done(function() {

        $("#uploadText").html("Done")

        $(document).click(function(){
          $("#uploadText").hide()
          $(".error").hide()
          $(".error_count").hide()
          location.reload();
        });
        
      });
    },
  
      // Optional. Called when the user closes the dialog without selecting a file
      // and does not include any parameters.
      cancel: function() {
      },
      // Optional. "preview" (default) is a preview link to the document for sharing,
      // "direct" is an expiring link to download the contents of the file. For more
      // information about link types, see Link types below.
      linkType: "direct", // or "preview"
  
      // Optional. A value of false (default) limits selection to a single file, while
      // true enables multiple file selection.
      multiselect: true, // or false
  
      // Optional. This is a list of file extensions. If specified, the user will
      // only be able to select files with these extensions. You may also specify
      // file types, such as "video" or "images" in the list. For more information,
      // see File types below. By default, all extensions are allowed.
      extensions: ['.png','.jpg'],
    };
  var button = Dropbox.createChooseButton(options_list);
  document.getElementById("dropbox").appendChild(button);
  
  
  $(function(){
    data = ['tom','john'];
    $('.textarea').atwho({at:"@", 'data':data});
  });