config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/users/sign_in')
  devise_for :users
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  resources :home, :dashboard
  resources :organizations do 
    resource :users
    resources :projects, only: [:index]
  end
  resources :projects do
   resources :project_activities
  end
  resources :project_activities, as: "assigned_projects", assigned: true
  resources :users do
    resources :projects
    get :autocomplete_user_email, :on => :collection
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :org_activities, as: :orgable, dependent: :destroy
  has_many :organizations, through: :org_activities
  has_many :project_activities, dependent: :destroy
  has_many :users, through: :project_activities, source: :projectable, source_type: 'User'
  #has_many :projects, through: :project_activities, source: :projectable, source_type: 'Project'
  #has_many :project_activities, as: :projectable
  #belongs_to :organizations
  accepts_nested_attributes_for :project_activities
  # validates :project_activities, presence: true
  validates :name, presence: true
  before_save :create_project_activity

  def create_project_activity
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :params_request_handled, only: [:index]

  def index
  end
  
  def new
    @project = Project.new
  end
  
  def edit
    
  end
  
  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end
  
  def create
    @project = current_organization.projects.create(project_params)
    @project.project_activities.create(projectable_id: current_user.id, projectable_type: "User", status: 'created')
    if not @project.errors.present?
      redirect_to projects_path
    else
      render :new
    end
  end
  
  def destroy
    redirect_to :back if @project.destroy
  end
  
  def show
    @project_activity = @project.project_activities.build
  end
  
  private
    
  def set_project
    @project = current_organization.projects.find_by_id(params[:id]) if params[:id].present?
    if not @project or not current_organization.projects.pluck(:id).include?(@project.id)
      redirect_to projects_path
    end
  end
  
  def project_params
    params.require(:project).permit!
  end
  
    
  # def params_request_handled
#     
    # if params[:user_id].present?
      # @projects = current_user.projects if current_user.id.to_s == params[:user_id]
      # @projects = [] if not @projects.present?
    # else
      # @projects = current_organization.projects if current_user.check_user_role('admin')
      # @projects = current_user.projects if not @projects.present?
    # end
  # end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message
  = f.text_field :name
  .actions
    = f.submit

app/views/projects/_project_list.html.haml
= link_to "create proj", new_project_path
%p#notice= notice
%h1 
%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"} Link
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= link_to 'Show',  new_project_project_activity_path(project)
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Proj Act',  project_project_activities_path(project)
%br/

app/views/projects/_select_project.html.haml
- if current_organization.projects.present?
  = form_tag  new_dashboard_path, method: :get do
    = hidden_field_tag :params_attr, params
    = select(:project_id,'', ["select project"] + @projects.select(:id, :name).collect{|proj| [proj.name, proj.id]},{prompt: "Please select project", selected: (@project.id rescue nil)},onchange: "this.form.submit();")
- else
  No more projects
  = link_to "Go back", projects_path

app/views/projects/edit.html.haml
%h1 Editing Users E
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
= link_to "create proj", new_project_path
%p#notice= notice
%h1 
%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"} Link
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= link_to 'Show',   project
        %td= link_to 'Edit', edit_project_path(project)
        - if can? :destroy, project
          %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Proj Act',  project_project_activities_path(project)
%br/

app/views/projects/new.html.haml
= render 'form'
= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice
= link_to 'Back', projects_path

= @project.name
=# render partial: "project_activities/assign_project"