config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/users/sign_in')
  devise_for :users
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  resources :home, :dashboard
  resources :organizations do 
    resource :users
    resources :projects, only: [:index]
  end
  resources :projects do
   resources :project_activities
  end
  resources :project_activities, as: "assigned_projects", assigned: true
  resources :users do
    resources :projects
    get :autocomplete_user_email, :on => :collection
  end
  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
   
   uniq_id :name # it is defined in common_method.rb
   has_many :org_activities #, as: :orgable
   has_many :users, through: :org_activities, source: :orgable, source_type: 'User'
   has_many :projects, through: :org_activities, source: :orgable, source_type: 'Project'
  # has_many :projects   
  validates :name, presence: true
  
  def check_project_is_belongs_to_organization_or_user?(project, user)
    (user.projects.pluck(:id).include?(project.id) or self.projects.pluck(:id).include?(project.id)) rescue false
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :set_organization, only: [:show, :edit, :update, :destroy]
  
  def index
    #@organizations = current_user.organizations
    @users = current_organization.users
    @projects = current_organization.projects
  end
  
  def new
    @organization = Organization.new
  end
  
  def edit
    @organization = Organization.find_by_id(params[:id])
  end
  
  def update
    @organization.update(organization_params)
    redirect_to @organization
  end
  
  def create
    @organization = current_user.organizations.create(organization_params)
    if not @organization.errors.present?
      redirect_to organizations_path
    else
      render :new
    end
  end
  
  def show
  end
  
  def destroy
    
  end
  
  private
  
  def set_organization
    @organization = (Organization.find_by_id(params[:id]) || current_organization)
  end
  
  def organization_params
    params.require(:organization).permit!
  end
  
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= form_for(@organization) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit

app/views/organizations/_select_organization_popup.html.haml
= form_tag  new_dashboard_path, method: :get do
  = hidden_field_tag :set_org, true
  = hidden_field_tag :params_attr, params
  = hidden_field_tag :check_page, true if params[:controller] == "project_activities"
  = select(:organization_id,'', @organizations.collect{|org| [org.name, org.id]},{prompt: "Please select organization", selected: (current_organization.id rescue nil)},onchange: "this.form.submit();")

app/views/organizations/edit.html.haml
%h1 Editing Users E
= render 'form'
= link_to 'Show', @organization
|
= link_to 'Back', users_path

app/views/organizations/index.html.haml
=# link_to "create user",  new_user_path 
=# link_to "User List",  users_path 
=# link_to "assigned project",  user_projects_path(user_id: current_user.id)
%p#notice= notice
%h1 
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{colspan: "3"} Link
  %tbody
    - current_user.organizations.each do |org|
      %tr
        %td= org.name
        %td= org.description
        %td= link_to 'Details', organization_path(org, :set_org => true)
        %td= link_to 'Edit', edit_organization_path(org)
        %td= link_to 'Destroy', org, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/organizations/new.html.haml
= render 'form'
= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
=# link_to "create user",  new_user_path 
=# link_to "User List",  users_path 
=# link_to "assigned project",  user_projects_path(user_id: current_user.id)
%h1 
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{colspan: "3"} Link
  %tbody
    %tr
      %td= current_organization.name
      %td= current_organization.description
      %td= link_to 'Projects', projects_path
      %td= link_to 'Edit', edit_organization_path(current_organization)
      %td= link_to 'Destroy', current_organization, method: :delete, data: { confirm: 'Are you sure?' }
%br/