config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/users/sign_in')
  devise_for :users
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  resources :home, :dashboard
  resources :organizations do 
    resource :users
    resources :projects, only: [:index]
  end
  resources :projects do
   resources :project_activities
  end
  resources :project_activities, as: "assigned_projects", assigned: true
  resources :users do
    resources :projects
    get :autocomplete_user_email, :on => :collection
  end
  

end

app/views/layouts/_breadcrum.html.haml
= render partial: "organizations/select_organization_popup"
- if @project.present?
  %label Project Name :
  = @project.name
- if current_user
  = current_user.email
%br/

app/views/layouts/_menu_bar.html.haml
- if can? :index, Organization
  = link_to "Organization list",  dashboard_index_path
- if can? :new, Organization
  = link_to "create Org", new_organization_path
- if can? :new, User
  = link_to "create user",  new_user_path 
- if can? :index, User
  = link_to "User List",  users_path

= link_to "Projects",  projects_path

- if can? :new, Project
  = link_to "new Projects",  new_project_path if current_organization
- if  @project.present? and can? :index, @project
  = link_to "assign project",   project_project_activities_path(:project_id => (params[:project_id].present? ? params[:project_id] : 0)) #if true @project
  = link_to "assigned project",   project_project_activities_path(:project_id => (params[:project_id].present? ? params[:project_id] : 0), assigned: true) #if true @project

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TestProjectWithPuma
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    - if current_user
      = flash[:alert]
      - flash[:alert] = nil
      = render partial: "layouts/breadcrum"
      = render partial: "layouts/menu_bar"
    %p#notice= notice
    = yield